// import type { Metadata } from "next";
// import ExperiencesContainer from "@/components/experience";
// import { experienceConfig } from "@/config/experienceConfig";
// import Footer from "@/components/footer";

// export const metadata: Metadata = {
//   title: "Experience - John Carlo",
//   description: "Generated by create next app",
// };

// export default function Experiences() {
//     const callFrom = Experiences.name.toLowerCase();
//     console.log(experienceConfig.contents)
//     return (
//     <>
//         <ExperiencesContainer 
//             experiences={experienceConfig.contents}
//             callFrom={callFrom}
//         />
//         <Footer />
//     </>
//     );
// }