import type { Metadata } from "next";

import Header from "@/components/header/Header";
import styles from "@/styles/techStack.module.css";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Tech Stack - John Carlo",
  description: "Generated by create next app",
};

export default function TechStack() {
    return (
        <>
            <Header 
                title="Technology Stack."
                navigationHref="/"
                intro={[
                    "At the core of every successful project is the right set of tools. This page showcases the technologies I use to design, build, and scale modern digital experiences. From robust backend frameworks to interactive frontend libraries, every tool in our stack is carefully chosen to deliver performance, scalability, and a seamless user experience.",
                    "Explore the languages, frameworks, and platforms that power our work across frontend, backend, databases, mobile, and more."
                ]}
            />
            <section className={styles.content}>
                <TechSection
                    title="Client-Side Development"
                    items={[
                        "JavaScript", 
                        "TypeScript", 
                        "React", 
                        "Next.js", 
                        "Vue.js", 
                        "Angular",
                        "Tailwind CSS",
                        "Bootsrap",
                        "SCSS",
                        "Styled Component",
                        "Vite",
                        "Material UI",
                        "Webpack",
                        "React Native & Expo",
                        "Swift",
                        "SwiftUI",
                        "XML",
                        "NativeBase",
                        "More Tools"
                    ]}
                />
                 <TechSection
                    title="Server-Side Development"
                    items={[
                        "Node.js", 
                        "Phython", 
                        "React", 
                        "Java", 
                        "PHP", 
                        "Laravel",
                        "MySQL",
                        "Supabase",
                        "JWT",
                        "REST",
                        "Firebase",
                        "MongoDB",
                        "Redis",
                        "Codeigniter",
                        "More Tools"
                    ]}
                />
                <TechSection
                    title="CMSt & No-Code Platforms"
                    items={[
                        "Wordpress", 
                        "Webflow", 
                        "Wix", 
                        "Strapi", 
                        "Bubble",
                        "Microsoft Power Platform",
                        "n8n",
                        "More Tools"
                    ]}
                />
                <TechSection
                    title="Developer Productivity Tools"
                    items={[
                        "Git", 
                        "Xcode", 
                        "VS code", 
                        "Slack", 
                        "Discord", 
                        "Teams",
                        "JIRA",
                        "More Tools"
                    ]}
                />
            </section>
            <Footer />
        </>
    );
}

// TechSection is defined as a separate component function here for modularity and reusability.
// It can be moved to its own file if desired, but keeping it here simplifies this page’s scope 
// and avoids extra imports for small, page-specific UI parts.
type TechSectionProps = {
  title: string;
  items: string[];
};

function TechSection({ title, items }: TechSectionProps) {
  return (
    <div className={styles["tech-section"]}>
      <h4>{title}</h4>
      <ul>
        {items.map((item, idx) => (
          <li key={idx}>{item}</li>
        ))}
      </ul>
    </div>
  );
}
