import type { Metadata } from "next";
import HomePage from "@/containers/home-page";

export const metadata: Metadata = {
  title: "John Carlo - Web and Mobile Developer",
  description: "Generated by create next app",
};

export default function Home() {
  return  <HomePage />;
}
